// This file is auto-generated by scripts/set-env.js
export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: "AIzaSyA4pIfS8mVsISewZ1vZA-SIiNxyJboHi58",
    authDomain: "accenturetest-e0dbb.firebaseapp.com",
    projectId: "accenturetest-e0dbb",
    storageBucket: "accenturetest-e0dbb.firebasestorage.app",
    messagingSenderId: "182645758432",
    appId: "1:182645758432:web:ba976dcd2689eac9fa3385",
    measurementId: "G-PM9E2QDZ6V"
  },
  remoteConfigDefaults: {
    show_delete_all: false
  }
};
