const fs = require('fs');
const path = require('path');

const dotEnvPath = path.join(__dirname, '../.env');
const envFileContent = fs.readFileSync(dotEnvPath, 'utf8');

const envVars = {};
envFileContent.split(/\r?\n/).forEach(line => {
  const [key, ...valueParts] = line.split('=');
  if (key && valueParts.length > 0) {
    const value = valueParts.join('=').replace(/^["']|["']$/g, '');
    envVars[key.trim()] = value.trim();
  }
});

const generateEnv = (isProd) => `// This file is auto-generated by scripts/set-env.js
export const environment = {
  production: ${isProd},
  firebaseConfig: {
    apiKey: "${envVars.VITE_FIREBASE_API_KEY}",
    authDomain: "${envVars.VITE_FIREBASE_AUTH_DOMAIN}",
    projectId: "${envVars.VITE_FIREBASE_PROJECT_ID}",
    storageBucket: "${envVars.VITE_FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${envVars.VITE_FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${envVars.VITE_FIREBASE_APP_ID}",
    measurementId: "${envVars.VITE_FIREBASE_MEASUREMENT_ID}"
  },
  remoteConfigDefaults: {
    show_delete_all: false
  }
};
`;

const devPath = path.join(__dirname, '../src/environments/environment.ts');
const prodPath = path.join(__dirname, '../src/environments/environment.prod.ts');

fs.writeFileSync(devPath, generateEnv(false));
fs.writeFileSync(prodPath, generateEnv(true));

console.log(`Environment variables synced to ${devPath} and ${prodPath}`);
